// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a03aea58-00b1-4b23-9a93-985bfef5c559",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_o6S8KZmqL",
    "aws_user_pools_web_client_id": "padm18ja8gk91ceg4rab9nupo",
    "aws_mobile_analytics_app_id": "9fb8c6a169aa477697bda21f3ade876c",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
